# -*- coding: utf-8 -*-
import json

# code, name_en, name_pt, capital_en, capital_pt
data = [
("DZ","Algeria","Argélia","Algiers","Argel"),
("AO","Angola","Angola","Luanda","Luanda"),
("BJ","Benin","Benin","Porto-Novo","Porto-Novo"),
("BW","Botswana","Botsuana","Gaborone","Gaborone"),
("BF","Burkina Faso","Burquina Faso","Ouagadougou","Uagadugu"),
("BI","Burundi","Burundi","Gitega","Gitega"),
("CV","Cabo Verde","Cabo Verde","Praia","Praia"),
("CM","Cameroon","Camarões","Yaoundé","Iaundé"),
("CF","Central African Republic","República Centro-Africana","Bangui","Bangui"),
("TD","Chad","Chade","N'Djamena","Ndjamena"),
("KM","Comoros","Comores","Moroni","Moroni"),
("CD","Democratic Republic of the Congo","República Democrática do Congo","Kinshasa","Kinshasa"),
("CG","Republic of the Congo","República do Congo","Brazzaville","Brazzaville"),
("DJ","Djibouti","Djibuti","Djibouti","Djibuti"),
("EG","Egypt","Egito","Cairo","Cairo"),
("GQ","Equatorial Guinea","Guiné Equatorial","Malabo","Malabo"),
("ER","Eritrea","Eritreia","Asmara","Asmara"),
("SZ","Eswatini","Essuatíni","Mbabane","Mbabane"),
("ET","Ethiopia","Etiópia","Addis Ababa","Adis Abeba"),
("GA","Gabon","Gabão","Libreville","Libreville"),
("GM","Gambia","Gâmbia","Banjul","Banjul"),
("GH","Ghana","Gana","Accra","Acra"),
("GN","Guinea","Guiné","Conakry","Conacri"),
("GW","Guinea-Bissau","Guiné-Bissau","Bissau","Bissau"),
("CI","Ivory Coast","Costa do Marfim","Yamoussoukro","Iamussucro"),
("KE","Kenya","Quênia","Nairobi","Nairóbi"),
("LS","Lesotho","Lesoto","Maseru","Maseru"),
("LR","Liberia","Libéria","Monrovia","Monróvia"),
("LY","Libya","Líbia","Tripoli","Trípoli"),
("MG","Madagascar","Madagascar","Antananarivo","Antananarivo"),
("MW","Malawi","Malawi","Lilongwe","Lilongwe"),
("ML","Mali","Mali","Bamako","Bamaco"),
("MR","Mauritania","Mauritânia","Nouakchott","Nuaquechott"),
("MU","Mauritius","Maurícia","Port Louis","Port Louis"),
("MA","Morocco","Marrocos","Rabat","Rabat"),
("MZ","Mozambique","Moçambique","Maputo","Maputo"),
("NA","Namibia","Namíbia","Windhoek","Windhoek"),
("NE","Niger","Níger","Niamey","Niamei"),
("NG","Nigeria","Nigéria","Abuja","Abuja"),
("RW","Rwanda","Ruanda","Kigali","Kigali"),
("ST","Sao Tome and Principe","São Tomé e Príncipe","São Tomé","São Tomé"),
("SN","Senegal","Senegal","Dakar","Dakar"),
("SC","Seychelles","Seicheles","Victoria","Victoria"),
("SL","Sierra Leone","Serra Leoa","Freetown","Freetown"),
("SO","Somalia","Somália","Mogadishu","Mogadíscio"),
("ZA","South Africa","África do Sul","Pretoria","Pretória"),
("SS","South Sudan","Sudão do Sul","Juba","Juba"),
("SD","Sudan","Sudão","Khartoum","Cartum"),
("TZ","Tanzania","Tanzânia","Dodoma","Dodoma"),
("TG","Togo","Togo","Lomé","Lomé"),
("TN","Tunisia","Tunísia","Tunis","Tunes"),
("UG","Uganda","Uganda","Kampala","Campala"),
("ZM","Zambia","Zâmbia","Lusaka","Lusaka"),
("ZW","Zimbabwe","Zimbábue","Harare","Harare"),
("AG","Antigua and Barbuda","Antígua e Barbuda","Saint John's","Saint John's"),
("AR","Argentina","Argentina","Buenos Aires","Buenos Aires"),
("BS","Bahamas","Bahamas","Nassau","Nassau"),
("BB","Barbados","Barbados","Bridgetown","Bridgetown"),
("BZ","Belize","Belize","Belmopan","Belmopan"),
("BO","Bolivia","Bolívia","Sucre","Sucre"),
("BR","Brazil","Brasil","Brasília","Brasília"),
("CA","Canada","Canadá","Ottawa","Ottawa"),
("CL","Chile","Chile","Santiago","Santiago"),
("CO","Colombia","Colômbia","Bogotá","Bogotá"),
("CR","Costa Rica","Costa Rica","San José","San José"),
("CU","Cuba","Cuba","Havana","Havana"),
("DM","Dominica","Dominica","Roseau","Roseau"),
("DO","Dominican Republic","República Dominicana","Santo Domingo","Santo Domingo"),
("EC","Ecuador","Equador","Quito","Quito"),
("SV","El Salvador","El Salvador","San Salvador","San Salvador"),
("GD","Grenada","Granada","Saint George's","Saint George's"),
("GT","Guatemala","Guatemala","Guatemala City","Cidade da Guatemala"),
("GY","Guyana","Guiana","Georgetown","Georgetown"),
("HT","Haiti","Haiti","Port-au-Prince","Port-au-Prince"),
("HN","Honduras","Honduras","Tegucigalpa","Tegucigalpa"),
("JM","Jamaica","Jamaica","Kingston","Kingston"),
("MX","Mexico","México","Mexico City","Cidade do México"),
("NI","Nicaragua","Nicarágua","Managua","Manágua"),
("PA","Panama","Panamá","Panama City","Cidade do Panamá"),
("PY","Paraguay","Paraguai","Asunción","Assunção"),
("PE","Peru","Peru","Lima","Lima"),
("KN","Saint Kitts and Nevis","São Cristóvão e Névis","Basseterre","Basseterre"),
("LC","Saint Lucia","Santa Lúcia","Castries","Castries"),
("VC","Saint Vincent and the Grenadines","São Vicente e Granadinas","Kingstown","Kingstown"),
("SR","Suriname","Suriname","Paramaribo","Paramaribo"),
("TT","Trinidad and Tobago","Trindade e Tobago","Port of Spain","Port of Spain"),
("US","United States","Estados Unidos","Washington, D.C.","Washington, D.C."),
("UY","Uruguay","Uruguai","Montevideo","Montevidéu"),
("VE","Venezuela","Venezuela","Caracas","Caracas"),
("AF","Afghanistan","Afeganistão","Kabul","Cabul"),
("AM","Armenia","Armênia","Yerevan","Erevã"),
("AZ","Azerbaijan","Azerbaijão","Baku","Baku"),
("BH","Bahrain","Bahrein","Manama","Manama"),
("BD","Bangladesh","Bangladesh","Dhaka","Daca"),
("BT","Bhutan","Butão","Thimphu","Timphu"),
("BN","Brunei","Brunei","Bandar Seri Begawan","Bandar Seri Begawan"),
("KH","Cambodia","Camboja","Phnom Penh","Phnom Penh"),
("CN","China","China","Beijing","Pequim"),
("CY","Cyprus","Chipre","Nicosia","Nicósia"),
("GE","Georgia","Geórgia","Tbilisi","Tbilisi"),
("IN","India","Índia","New Delhi","Nova Délhi"),
("ID","Indonesia","Indonésia","Jakarta","Jacarta"),
("IR","Iran","Irã","Tehran","Teerã"),
("IQ","Iraq","Iraque","Baghdad","Bagdá"),
("IL","Israel","Israel","Jerusalem","Jerusalém"),
("JP","Japan","Japão","Tokyo","Tóquio"),
("JO","Jordan","Jordânia","Amman","Amã"),
("KZ","Kazakhstan","Cazaquistão","Astana","Astana"),
("KW","Kuwait","Kuwait","Kuwait City","Cidade do Kuwait"),
("KG","Kyrgyzstan","Quirguistão","Bishkek","Bisqueque"),
("LA","Laos","Laos","Vientiane","Vientiane"),
("LB","Lebanon","Líbano","Beirut","Beirute"),
("MY","Malaysia","Malásia","Kuala Lumpur","Kuala Lumpur"),
("MV","Maldives","Maldivas","Malé","Malé"),
("MN","Mongolia","Mongólia","Ulaanbaatar","Ulan Bator"),
("MM","Myanmar","Mianmar","Naypyidaw","Naypyidaw"),
("NP","Nepal","Nepal","Kathmandu","Catmandu"),
("KP","North Korea","Coreia do Norte","Pyongyang","Pyongyang"),
("OM","Oman","Omã","Muscat","Mascate"),
("PK","Pakistan","Paquistão","Islamabad","Islamabade"),
("PS","Palestine","Palestina","Ramallah","Ramallah"),
("PH","Philippines","Filipinas","Manila","Manila"),
("QA","Qatar","Catar","Doha","Doha"),
("SA","Saudi Arabia","Arábia Saudita","Riyadh","Riade"),
("SG","Singapore","Singapura","Singapore","Singapura"),
("KR","South Korea","Coreia do Sul","Seoul","Seul"),
("LK","Sri Lanka","Sri Lanka","Colombo","Colombo"),
("SY","Syria","Síria","Damascus","Damasco"),
("TJ","Tajikistan","Tajiquistão","Dushanbe","Dushanbe"),
("TH","Thailand","Tailândia","Bangkok","Bangcoc"),
("TL","Timor-Leste","Timor-Leste","Dili","Díli"),
("TR","Turkey","Turquia","Ankara","Ancara"),
("TM","Turkmenistan","Turcomenistão","Ashgabat","Asgabate"),
("AE","United Arab Emirates","Emirados Árabes Unidos","Abu Dhabi","Abu Dhabi"),
("UZ","Uzbekistan","Uzbequistão","Tashkent","Tasquente"),
("VN","Vietnam","Vietnã","Hanoi","Hanói"),
("YE","Yemen","Iêmen","Sana'a","Sanaa"),
("AL","Albania","Albânia","Tirana","Tirana"),
("AD","Andorra","Andorra","Andorra la Vella","Andorra-a-Velha"),
("AT","Austria","Áustria","Vienna","Viena"),
("BY","Belarus","Bielorrússia","Minsk","Minsk"),
("BE","Belgium","Bélgica","Brussels","Bruxelas"),
("BA","Bosnia and Herzegovina","Bósnia e Herzegovina","Sarajevo","Sarajevo"),
("BG","Bulgaria","Bulgária","Sofia","Sófia"),
("HR","Croatia","Croácia","Zagreb","Zagreb"),
("CZ","Czech Republic","República Tcheca","Prague","Praga"),
("DK","Denmark","Dinamarca","Copenhagen","Copenhague"),
("EE","Estonia","Estônia","Tallinn","Tallinn"),
("FI","Finland","Finlândia","Helsinki","Helsinque"),
("FR","France","França","Paris","Paris"),
("DE","Germany","Alemanha","Berlin","Berlim"),
("GR","Greece","Grécia","Athens","Atenas"),
("HU","Hungary","Hungria","Budapest","Budapeste"),
("IS","Iceland","Islândia","Reykjavik","Reykjavik"),
("IE","Ireland","Irlanda","Dublin","Dublin"),
("IT","Italy","Itália","Rome","Roma"),
("XK","Kosovo","Kosovo","Pristina","Pristina"),
("LV","Latvia","Letônia","Riga","Riga"),
("LI","Liechtenstein","Liechtenstein","Vaduz","Vaduz"),
("LT","Lithuania","Lituânia","Vilnius","Vilnius"),
("LU","Luxembourg","Luxemburgo","Luxembourg","Luxemburgo"),
("MT","Malta","Malta","Valletta","Valeta"),
("MD","Moldova","Moldávia","Chisinau","Chisinau"),
("MC","Monaco","Mônaco","Monaco","Mônaco"),
("ME","Montenegro","Montenegro","Podgorica","Podgorica"),
("NL","Netherlands","Países Baixos","Amsterdam","Amsterdã"),
("MK","North Macedonia","Macedônia do Norte","Skopje","Escópia"),
("NO","Norway","Noruega","Oslo","Oslo"),
("PL","Poland","Polônia","Warsaw","Varsóvia"),
("PT","Portugal","Portugal","Lisbon","Lisboa"),
("RO","Romania","Romênia","Bucharest","Bucareste"),
("RU","Russia","Rússia","Moscow","Moscou"),
("SM","San Marino","San Marino","San Marino","San Marino"),
("RS","Serbia","Sérvia","Belgrade","Belgrado"),
("SK","Slovakia","Eslováquia","Bratislava","Bratislava"),
("SI","Slovenia","Eslovênia","Ljubljana","Liubliana"),
("ES","Spain","Espanha","Madrid","Madri"),
("SE","Sweden","Suécia","Stockholm","Estocolmo"),
("CH","Switzerland","Suíça","Bern","Berna"),
("UA","Ukraine","Ucrânia","Kyiv","Kiev"),
("GB","United Kingdom","Reino Unido","London","Londres"),
("VA","Vatican City","Vaticano","Vatican City","Cidade do Vaticano"),
("AU","Australia","Austrália","Canberra","Canberra"),
("FJ","Fiji","Fiji","Suva","Suva"),
("KI","Kiribati","Kiribati","Tarawa","Tarawa"),
("MH","Marshall Islands","Ilhas Marshall","Majuro","Majuro"),
("FM","Micronesia","Micronésia","Palikir","Palikir"),
("NR","Nauru","Nauru","Yaren","Yaren"),
("NZ","New Zealand","Nova Zelândia","Wellington","Wellington"),
("PW","Palau","Palau","Ngerulmud","Ngerulmud"),
("PG","Papua New Guinea","Papua-Nova Guiné","Port Moresby","Port Moresby"),
("WS","Samoa","Samoa","Apia","Apia"),
("SB","Solomon Islands","Ilhas Salomão","Honiara","Honiara"),
("TO","Tonga","Tonga","Nuku'alofa","Nuku'alofa"),
("TV","Tuvalu","Tuvalu","Funafuti","Funafuti"),
("VU","Vanuatu","Vanuatu","Port Vila","Port Vila"),
]

def flag_emoji(code):
    return "".join(chr(0x1F1E6 + ord(c) - ord('A')) for c in code.upper())

countries = []
for code, en, pt, cap_en, cap_pt in data:
    countries.append({
        "code": code,
        "en": en,
        "pt": pt,
        "capitalEn": cap_en,
        "capitalPt": cap_pt,
        "flag": flag_emoji(code) if len(code) == 2 else ""
    })

with open("countries.json", "w", encoding="utf-8") as f:
    json.dump(countries, f, ensure_ascii=False, indent=2)

print("total:", len(countries))
